version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:10.11
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  mysql_data:
    driver: local